donasi/urls.py
from django.urls import path, include
from . import views

app_name = 'donasi'

urlpatterns = [
    path('', views.donasi, name = "donasi"),
    path('<name>/', views.detail, name = "detail"),
]

donasibarang/urls.py
from django.urls import path, include
from . import views

app_name = 'donasibarang'

urlpatterns = [
    path('', views.donasibarang, name = "donasibarang"),
    path('<name>/', views.detailbarang, name = "detailbarang"),
]

homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = "index"),
]

lawancorona/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('donasi/', include('donasi.urls')),
    path('donasibarang/', include('donasibarang.urls'))
]

donasi/models.py
from django.db import models

# Create your models here.

donasibarang/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

donasi/views.py
from django.shortcuts import render

# Create your views here.
def donasi(request):
    return render(request, 'donasi.html')

def detail(request, nama):
    return render(request, 'donasi.html')

donasibarang/views.py
from django.shortcuts import render

# Create your views here.
def donasibarang(request):
    return render(request, 'donasibarang.html')

def detailbarang(request, nama):
    return render(request, 'donasibarang.html')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

donasi/templates/donasi.html
<!DOCTYPE html>
{% extends "base/base.html" %}

{% load static %}

<!-- HEAD -->

{% block head %}
<link rel="stylesheet" href="{% static '/css/donasi.css' %}">
<title>Corona-Dingdong | Donasi</title>
{% endblock %}

<!-- CONTENT -->

{% block content %}
<div id="container-donasi">
    <form action="">
        <input type="text" name="search" id="search" placeholder="ketik nama RS atau klinik di sini">
    </form>

    <div class="filter">
        <label for="choose">Filter: </label>
        <select id="choose">
            <option value="all">All</option>
            <option value="haha">haha</option>
            <option value="hihi">hihi</option>
            <option value="huhu">huhu</option>
        </select>
        <button class="btn btn-light filter-btn" id="filter-btn">filter</button>
    </div>

    <div id="list"></div>
</div>
{% endblock %}

<!-- SCRIPT -->

{% block script %}
<!-- Javascript, JQuery, AJAX -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

<!-- donasi.js -->
<script src="{% static 'js/donasi.js' %}"></script>
{% endblock %}

donasibarang/templates/donasibarang.html
<!DOCTYPE html>
{% extends "base/base.html" %}

{% load static %}

<!-- HEAD -->

{% block head %}
<link rel="stylesheet" href="{% static '/css/donasibarang.css' %}">
<title>Corona-Dingdong | Donasi</title>
{% endblock %}

<!-- CONTENT -->

{% block content %}
<div id="container-donasi">
    <form action="">
        <input type="text" name="search" id="search" placeholder="ketik nama RS atau klinik di sini">
    </form>

    <div class="filter">
        <label for="choose">Filter: </label>
        <select id="choose">
            <option value="all">All</option>
            <option value="haha">haha</option>
            <option value="hihi">hihi</option>
            <option value="huhu">huhu</option>
        </select>
        <button class="btn btn-light filter-btn" id="filter-btn">filter</button>
    </div>

    <div id="list"></div>
</div>
{% endblock %}

<!-- SCRIPT -->

{% block script %}
<!-- Javascript, JQuery, AJAX -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

<!-- donasi.js -->
<script src="{% static 'js/donasibarang.js' %}"></script>
{% endblock %}

homepage/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- META TAG -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Import CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    {% block static %}{% endblock %}

    <!-- Import Font -->
    <link href="https://fonts.googleapis.com/css?family=Chewy&display=swap" rel="stylesheet">

    <!-- Import from fontawesome.com -->
    <script src="https://kit.fontawesome.com/26197ec3bf.js"></script>

    {% block head %}{% endblock %}
</head>
<body>
    <div id="container" class="position-relative">
        <!-- Navbar -->
        <div class="fixed-top b-blue">
          <nav class="navbar navbar-default navbar-expand-md navbar-light">
            <a class="navbar-brand" href=""><img src="{% static 'img/corona-help.svg' %}" alt=""></a>
            <hr>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link{% if url_name == 'index' %} active{% endif %}" href="{% url 'homepage:index' %}">Beranda</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link{% if url_name == 'donasi' %} active{% endif %}" href="{% url 'donasi:donasi' %}">Donasi</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link{% if url_name == 'tentang' %} active{% endif %}" href="">RS in need</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link{% if url_name == 'testimoni' %} active{% endif %}" href="">FAQ</a>
                </li>
              </ul>
              <ul class="ml-auto navbar-nav">
                <li class="navbar-right nav-item">
                    <a class="nav-link{% if url_name == 'testimoni' %} active{% endif %}" href="">Login</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>

        <!-- Content -->
        {% block content %}{% endblock %}

        <!-- Footer -->
        <footer class="position-absolute b-blue-muda d-flex justify-content-between align-items-center">
            <div class="col text-center">
              <img class="footer-img img-fluid" src="{% static '/img/ui.png' %}" alt="">
              Developed by Fasilkom UI
            </div>
            <div class="col text-center">
              Corona-Dingdong Team
            </div>
        </footer>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src={% static 'js/homepage.js' %}></script>
    {% block script %}{% endblock %}
</body>
</html>

homepage/templates/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %} <title>Corona-Dingdong | Homepage</title> {% endblock %}
{% block content %}
<section id="homepage">
    <div>
        <div class="container-fluid">
            <div class="homepage">
                <div class="row row-hp">
                    <div class="col-8">
                        <h1 class="hp-text">
                            Bantu RS dan Klinik di Jakarta melawan Covid-19!
                        </h1>
                        <hr class="hp-hr">
                        <h5 class="text-center">
                            Ditengah pandemi Covid-19 yang memakan banyak korban, banyak rumah sakit dan klinik di jakarta membutuhkan bantuan baik uang maupun barang karena persediaannya yang semakin terbatas
                        </h5>
                    </div>
                    <div class="col-4">
                        <div class="row row-info">
                            <div class="col">
                                <img class="odp" src="{% static '/img/odp.svg' %}" alt="">
                            </div>
                            <div class="col">
                                1,306
                            </div>
                            <div class="col">
                                Orang dalam pemantauan
                            </div>
                        </div>
                        <div class="row row-info align-content-center">
                            <div class="col align-content-center">
                                <img class="pdp" src="{% static '/img/pdp.svg' %}" alt="">
                            </div>
                            <div class="col align-content-center">
                                528
                            </div>
                            <div class="col">
                                Pasien dalam pengawasan
                            </div>
                        </div>
                        <div class="row row-info">
                            <div class="col-4">
                                <img class="positif" src="{% static '/img/positif.svg' %}" alt="">
                            </div>
                            <div class="col-4">
                                450
                            </div>
                            <div class="col-4">
                                Kasus positif
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            Sumber: corona.jakarta.go.id
                        </div>
                    </div>
                </div>

                <div class="row row-hp text-center content">
                    <div class="col">
                        <img class="img-content" src="{% static '/img/img-1.svg' %}" alt="">
                    </div>
                    <div class="col">
                        <img class="img-content" src="{% static '/img/img-2.svg' %}" alt="">
                    </div>
                    <div class="col">
                        <img class="img-content" src="{% static '/img/img-3.svg' %}" alt="">
                    </div>
                </div>

                <div class="row  row-hp">
                    <div class="col">
                        <img class="img-donate" src="{% static '/img/donate.svg' %}" alt="">
                    </div>
                    <div class="col-8 text-right">
                        <h3 class="">
                            Kamu ingin membantu Rumah Sakit dan Klinik di jakarta agar bisa merawat lebih banyak korban dari pandemi Covid-19 ini?
                        </h3>
                        <input type="submit" class="button bt-blue" value="Donasi Sekarang!">
                    </div>
                </div>

                <div class="row  row-hp">
                    <div class="col-8">
                        <h3 class="">
                            Kamu ingin membantu Rumah Sakit dan Klinik di jakarta agar bisa merawat lebih banyak korban dari pandemi Covid-19 ini?
                        </h3>
                        <input type="submit" class="button bt-green" value="Gabung Sekarang!">
                    </div>
                    <div class="col text-right">
                        <img class="img-donate" src="{% static '/img/need-donation.svg' %}" alt="">
                    </div>
                </div>

                <div class="text-center">
                    <button onclick="scrollToTop()" class="to-top">
                        <img class="arrow" src="{% static 'img/arrow.svg' %}" alt="">
                        Kembali ke atas
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}